config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'home#index'

  resources :events do
    collection do
      get 'search', to: 'events#event_search', as: :search
      post 'search', to: 'events#post_event_search'
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  acts_as_taggable_on :themes
  acts_as_followable
  acts_as_likeable

  after_commit lambda {
    ::SnoopWorker.perform_async id
  }, on: :create

  has_and_belongs_to_many :users
  belongs_to :creator, class_name: 'User', foreign_key: :creator_id, required: true
  validates_presence_of :title, :city, :date_start, :date_end


  scope :by_tags, ->(tag_list)  { tagged_with(tag_list, any: true) }
  scope :by_start, ->(start, end_date) { where(date_start: start.to_datetime..end_date.to_datetime) }
  scope :by_city, ->(city) { where(city: city) }


end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_and_belongs_to_many :events, class_name: 'Event'
  has_many :created_events, class_name: 'Event', foreign_key: :creator_id
  acts_as_taggable_on :interests
  acts_as_follower
  acts_as_liker

  def offline!
    redis.setbit('user_appearance', id, 0)
  end

  def offline?
    redis.getbit('user_appearance', id).zero?
  end

  def online
    redis.setbit('user_appearance', id, 0)
  end

  def online?
    redis.getbit('user_appearance', id) == 1
  end


  private

  def redis
    Redis.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :get_event, only: %i[show edit destroy update]
  before_action :authenticate_user!, only: %i[new edit :destroy]
  def index
   @events = Event.all
  end

  def show; end

  def new
    @event = Event.new
    @event.creator = current_user
  end

  def create
    @event = Event.new event_params.to_hash.except('theme_list')
    @event.theme_list.add(event_params['theme_list'], parse: true)
    if @event.save
      redirect_to event_path(@event.id),
                  notice: %(Cобытие #{@event.title} успешно создано)
    else
      redirect_to  new_event_path, alert: 'Произошла ошибка!'
    end
  end

  def edit; end

  def update
    @event.update event_params.to_hast.except('theme_list')
  end

  def destroy
    title = @event.title
    @event.delete
    redirect_to events_path, alert: %(Событие #{title} отменено)
  end

  def event_search
    if current_user
      redis = Redis.new
      if redis.exists %(user:preferences:#{current_user.id})
        @setting = redis.hgetall( %(user:preferences:#{current_user.id})).to_hash
      end
    end
  end

  def post_event_search
    body = JSON.parse params['request']
    ret = []
    if 'on' == body['save']
      settings = body.except('save', 'user_id').to_a.flatten
      Redis.new.hmset %(user:preferences:#{body['user_id']}), settings
    end
    if body['theme_list'].present?
      tags = body['theme_list'].split(',').map { |el| %("#{el}") }
      ret << %(by_tags(#{tags}))
    end
    ret << %(by_city("#{body['city']}")) if body['city'].present?
    if body['date_start_min'].present? && body['date_start_max'].present?
      ret << %(by_start("#{body['date_start_min']}","#{body['date_start_max']}"))
    end
    render json: Event.class_eval(ret.join('.'))
  end

  private


  def get_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(
      :id, :date_start, :date_end, :place,
      :city, :title, :creator_id, :theme_list
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  after_action(only: [:create]) do
    current_user.online!
  end

  before_action(only: [:destroy]) do
    current_user.offline!
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-primary'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def get_value_safe(hsh, key)
    begin
      return hsh.fetch key, ''
    rescue NameError
      return ''
    end
  end
end

app/views/events/_form.html.slim
= simple_form_for event do |f|
  = f.input :title, lable: 'Название события',
          error: 'Должно быть заполнено'
  = f.input :city, label: 'Город',
          error: 'Должно быть заполнено'
  = f.input :place, label: 'Место проведения',
          hint: 'Если оставить пустым, то событие считается обшегородским'
  = f.input :date_start,  html5: true, label: 'Дата начала',
          input_html: { id: 'event_date_start' }
  = f.input :date_end,as: :datetime, html5: true, label: 'Дата завершения',
          input_html: { id: 'event_date_end' }
  = f.input :theme_list, label: 'Темы события',
          input_html: { value: event.theme_list.to_s }
  = f.input :creator_id, as: :hidden,
          input_html: { value: event.creator_id }
  = f.button :submit

app/views/events/edit.html.slim
= render 'form', event: @event

app/views/events/event_search.html.slim
form#event_form

  .form-group
    label Имя города
    input [type="text"
    class="form-control"
    id="city"
    aria-describedby="emailHelp"
    placeholder="Введите город"
    value=(get_value_safe(@setting, 'city') ) ]

  .form-group
    label Интересующие темы
    input [type="text"
    class="form-control"
    id="theme_list"
    aria-describedby="emailHelp"
    placeholder="Введите тему или несолько тем через запятую"
    value=(get_value_safe(@setting, 'theme_list')) ]

  .form-group
    label Дата начала события, не ранее
    #event_date_start_min.input-group.date data-target-input="nearest"
      input.form-control.datetimepicker-input data-target="#event_date_start_min" type="text"  /
      .input-group-append data-target="#event_date_start_min" data-toggle="datetimepicker" value=get_value_safe(@setting, 'date_start_min')
        .input-group-text
          i.fa.fa-calendar
      - if @setting.present?
        input [type="hidden" id="event_date_start_min_value"  value=get_value_safe(@setting, 'date_start_min') ]

  .form-group
    label Дата начала события, не позднее
    #event_date_start_max.input-group.date data-target-input="nearest"
      input.form-control.datetimepicker-input data-target="#event_date_start_max" type="text"  /
      .input-group-append data-target="#event_date_start_max" data-toggle="datetimepicker" value=get_value_safe(@setting, 'date_start_max')
        .input-group-text
          i.fa.fa-calendar
      - if @setting.present?
        input [type="hidden" id="event_date_start_max_value" value=get_value_safe(@setting, 'date_start_max') ]

  - if current_user
    .form-check.mb-3
      input [type="checkbox" class="form-check-input" id="save_preferences"]
        label.form-check-label Сохранить настройки поиска?
      input (type='hidden' value="#{current_user.id}" id="current_user_id" )

  button#event_search_submit [type="submit" class="btn btn-primary" ] Искать

.row#result_row

app/views/events/index.html.slim
h1 Events#index
p Find me in app/views/events/index.html.slim

app/views/events/new.html.slim
= render 'form', event: @event

app/views/events/show.html.slim
h1 Events#show
p Find me in app/views/events/show.html.slim

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title CityOfEvents
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


  body

    = render 'partials/navbar'

    - flash.each do |type, content|
      = render 'partials/flash', type: type, content: content

    .container
      = yield

app/views/partials/_flash.html.slim
div [class=%(alert #{bootstrap_class_for(type)} alert-dismissible fade show)  role="alert"]
  button [type="button" class="close" data-dismiss="alert" data-aria-label="Close"]
    span [aria-hidden="true"] &times;
  .text
    = content

app/views/partials/_navbar.html.slim
nav class="navbar navbar-expand-lg navbar-light bg-light"
  = link_to 'City Events', root_path, class: 'navbar-brand'
  button [
  class="navbar-toggler"
  type="button"
  data-toggle="collapse"
  data-target="#navbarSupportedContent"
  aria-controls="navbarSupportedContent"
  aria-expanded="false"
  aria-label="Toggle navigation"]
    span class="navbar-toggler-icon"


  .collapse.navbar-collapse id="navbarSupportedContent"
    ul.navbar-nav.mr-auto
      - if user_signed_in?
        li class=(['nav-item', current_page?('/events/new') ? 'active' : ''])
          = link_to 'Cоздать Событие', new_event_path, class: 'nav-link'

      li class=(['nav-item', current_page?('/events/search') ? 'active' : ''])
        = link_to 'Поиск Событий', search_events_path, class: 'nav-link'
      li class="nav-item dropdown"
        a [class="nav-link dropdown-toggle"
          href="#" id="navbarDropdown"
          role="button"
          data-toggle="dropdown"
          aria-haspopup="true"
          aria-expanded="false"]   Действия пользователя
        .dropdown-menu aria-labelledby="navbarDropdown"
          - unless  user_signed_in?
            = link_to 'Регистрация', new_user_registration_path, class: 'dropdown-item'
            = link_to 'Войти', new_user_session_path, class: 'dropdown-item'
          - else
            = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'dropdown_item'